apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-joark-mottak
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 30m
      memory: 256Mi
  webproxy: true
  envFrom:
    - secret: serviceuser-srvdagpenger-joark-mottak
  kafka:
    pool: "{{ kafka-pool }}"
  secureLogs:
    enabled: true
