apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-joark-mottak
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 300m
      memory: 512Mi
  webproxy: true
  envFrom:
    - secret: serviceuser-srvdagpenger-joark-mottak
  kafka:
    pool: {{ kafka-pool }}
  secureLogs:
    enabled: true