name: Build and deploy

on:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  build:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - uses: gradle/wrapper-validation-action@v3.3.1
      - uses: gradle/gradle-build-action@v3.3.1
        env:
          # Eksluder test dependencies
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: compileClasspath|runtimeClasspath
        with:
          gradle-version: wrapper
          dependency-graph: generate-and-submit
          arguments: --configuration-cache build --info

      - name: docker-build-push
        uses: nais/docker-build-push@v0
        if: github.ref == 'refs/heads/main'
        id: docker-build-push
        with:
          byosbom: dependency-graph-reports/build_and_deploy-build.json
          team: teamdagpenger
          push_image: true # optional, default true
          tag: ${{ github.sha }}
          dockerfile: Dockerfile # optional, default Dockerfile
          docker_context: . # optional, default .
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-dev:
    name: Deploy to dev
    needs: [build]
    if: github.ref == 'refs/heads/main'
    environment: dev-gcp
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/nais.yaml
          VAR: image=${{ needs.build.outputs.image }}
          VARS: nais/dev-vars.yaml
          PRINT_PAYLOAD: true

  deploy-prod:
    name: Deploy to Production
    needs: [build]
    if: github.ref == 'refs/heads/main'
    environment: prod-gcp
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/nais.yaml
          VAR: image=${{ needs.build.outputs.image }}
          VARS: nais/prod-vars.yaml
          PRINT_PAYLOAD: true
